language: python
python:
- '3.4'
- '3.5'
script: python -m unittest
notifications:
  slack:
    secure: NRW2mzKwbCfPG1SHQj54EtMkilaXL8qsXC6N8sUexiELI0WZHp4sEjsrT1EB4/ELuhHmW0fX295/xhURUSICTpbIYYmmYKCUy25RIbdtm38a3v4h/vTHXoU/nrkBEu1oRcUt51t5BbWZ0BPMxY0N3W2nbI36+oVy67BUEbPAqrnTpb3IYsrZ/KJj90NqV6mYFZAn90pGhFqjRwNR61CFPJpM5kukDzu6pO9FPGsNOzq/o+et2DNFGAF4mrlJpOJwg3jg/YdMz+/uL7+J1ooaHtLt9d5wmsvJwvoHSvJwuul0taElQ8js/Q4J7o1xWPSb3D28ZX7bpQtpPoTs6nGnh4fyStSFaRucnPGcH2xXvA8MlSdVzwwydQay3Mu5dQ+SWT/mfgRJHTLjreh/ghOCBylv7v0jG2NxgSaKgGzMSy7YY7b6duAck60dVGgWS/blGqbBo50vAHo65AygnpN1wWhVhNyimUJ7Ay0UFzpeCahWsazaY3rHUql4OvFBaeF8mxrkho/KNiMWbP2huVtjwEK0naWnNWggk2PBJlKc9ToWqm/+e0Da6YHTWz9CTyOGCkHqIwxl3zNlQT9boOrTUpJUrvbaKt/q2ABC5xCsIxPKkqwGT7XJ7UdUX5OkO0IH21Rtx/R6FBvrt78V1rimjSsVUKyCpxow1yPbcz9f/XE=
